services:
  postgres:
    image: postgres:15
    container_name: uespi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: uespi_connect
      POSTGRES_USER: uespi_user
      POSTGRES_PASSWORD: uespi123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - studio-network

  backend:
    build: ./backend
    container_name: uespi-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - livekit
    networks:
      - studio-network

  frontend:
    build: ./frontend
    container_name: uespi-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - studio-network

  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit
    restart: unless-stopped
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"

    command: --config /etc/livekit.yaml

    volumes:
      - ./livekit.yaml:/etc/livekit.yaml

    networks:
      - studio-network

  adminer:
    image: adminer
    container_name: uespi-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - studio-network

volumes:
  postgres_data:

networks:
  studio-network:
    driver: bridge
