services:
  uespi-fe:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: uespi-fe
    ports:
      - "80:80"
    networks:
      - uespi_net
    volumes:
      - ./:/app
      - /app/node_modules
      - ./shared-storage:/shared-storage:ro
    stdin_open: true
    tty: true

volumes:
  db_data:

networks:
  uespi_net:
    driver: bridge